CLASS LHC_ZI_ACHEAD DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.

    METHODS GET_INSTANCE_AUTHORIZATIONS FOR INSTANCE AUTHORIZATION
      IMPORTING KEYS REQUEST REQUESTED_AUTHORIZATIONS FOR ZI_ACHEAD RESULT RESULT.

    METHODS GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
      IMPORTING REQUEST REQUESTED_AUTHORIZATIONS FOR ZI_ACHEAD RESULT RESULT.

ENDCLASS.

CLASS LHC_ZI_ACHEAD IMPLEMENTATION.

  METHOD GET_INSTANCE_AUTHORIZATIONS.
  ENDMETHOD.

  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.

ENDCLASS.
